### ISSUE TITLE
[NumberGuesser] Число

### ISSUE THREAD

**Issue by pavel-b-novikov** [NastyaTimoshenko/nsudotnet#2]
Если я введу с клавиатуры строку (не содержащую q, разумеется) - программа упадет с exception-ом.

**Comment by NastyaTimoshenko** [comment]
Исправила

**Comment by pavel-b-novikov** [comment]
Без exception-а перепишите пожалуйста

**Comment by NastyaTimoshenko** [comment]
Переписала
