### ISSUE TITLE
[LinesCounter] line.StartsWith("//")

### ISSUE THREAD

**Issue by pavel-b-novikov** [NastyaTimoshenko/nsudotnet#5]
Случается и такое, что в строках кода сначала идет табуляция, а только потом эти два слэша. В этом случае строка так же считается не несущей никакого смысла. 
А ещё бывают в принципе строки, заполненные пробельными символами. Их учитывать так же не надо. 
А ещё это всё надо делать не используя .Trim/.Substring и не создавая лишних строк.

**Comment by NastyaTimoshenko** [comment]
Исправила

**Comment by pavel-b-novikov** [comment]
То есть по вашей логике вначале строки может быть только один символ табуляции?

**Comment by pavel-b-novikov** [comment]
А что вы пытаетесь сделать этой проверкой? О_о
```csharp
!(line[i] >= '0' && line[i] <= '9')
```

**Comment by NastyaTimoshenko** [comment]
Не логично.Исправила
Хотела проверить,что это не число но это плохой способ,заменила на char.IsDigit(line[i])
