### ISSUE TITLE
[Enigma] Не списано

### ISSUE THREAD

**Issue by pavel-b-novikov** [NastyaTimoshenko/nsudotnet#6]
Ну и откуда вы сдули энигму, признавайтесь. Она же у вас даже не компилируется.

**Comment by NastyaTimoshenko** [comment]
Моя,у меня компилируется и работает,возможно не правильно скинула.Скинула ее еще раз

**Comment by pavel-b-novikov** [comment]
![image](https://user-images.githubusercontent.com/2521412/40587900-c50465a8-61ff-11e8-9322-330c55b868d2.png)
Вы меня дурите, только я никак не могу понять где. Да и Settings.Designer.cs в энигме - крайне странное явление

**Comment by NastyaTimoshenko** [comment]
Добавила скрины в качестве ответа

**Comment by pavel-b-novikov** [comment]
Извините, я не принимаю задачи по скринам

**Comment by NastyaTimoshenko** [comment]
Раскидала Enigma на несколько файлов.Загрузила ее под названием Enigma2.Enigma2 компилируется?

**Comment by pavel-b-novikov** [comment]
Извините, но давайте-ка старую доделаем. А то я не могу в репозиторий с другим именем оценку ставить.

**Comment by NastyaTimoshenko** [comment]
Так это та же самая Enigma,только я разбила ее на 4файла.Я могу выгрузить ее в тот репозиторий,где предыдущая была.Просто чтобы починить вариант c одним файлом,нужно понять в чем ошибка,в то время как у меня она компилируется

**Comment by pavel-b-novikov** [comment]
Слушайте, ради интереса - а поставьте, пожалуйста, брекпоинт в студии на первый же if в методе Main вашей энигмы (не разбитой на несколько файлов), сделайте скриншот студии, которая стоит на этой точке останова и отправьте мне.

**Comment by pavel-b-novikov** [comment]
А не, пардон, открыл в 17й студии и понял основную мысль. Приношу извинения за доставленные неудобства. 
Откуда вы узнали о локальных функциях и зачем они вам здесь?

**Comment by NastyaTimoshenko** [comment]
Чтобы не создавать других файлов,обойтись одним,узнала практическим путем,ошибок не получила

**Comment by pavel-b-novikov** [comment]
Ладно, черт с ним
